### ISSUE TITLE
id-iki bloków w sekcji about-us

### ISSUE THREAD

**Issue by 84lukaszkaminski** [infoshareacademy/jfdzw1-greenteam#8]
Nie jestem przekonany co do wartości id bloków div na formularzu. One, two, three nie są wartościami semantycznymi. Niech nazwy wskazują na coś - niech nadają sens ich istnieniu, np. Input-email, input-user-name, itp.
Podobnie z id buttons. Czy kolejny blok z buttonami będzie miał id="buttons2"?

**Comment by wojtexnaj** [comment]
Done.
